# Generated by Django 5.1.3 on 2024-11-10 13:35

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("about", models.TextField()),
                (
                    "domain",
                    models.CharField(
                        choices=[
                            ("gambling", "Gambling"),
                            ("gamedev", "Gamedev"),
                            ("fintech", "Fintech"),
                            ("outsource", "Outsource"),
                            ("ecommerce", "Ecommerce"),
                        ],
                        max_length=30,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("location", models.CharField(max_length=255)),
                ("website", models.URLField()),
                ("employee_count", models.PositiveIntegerField()),
                ("is_verified", models.BooleanField(default=False)),
                ("is_hiring", models.BooleanField(default=False)),
                ("has_internship", models.BooleanField(default=False)),
            ],
        ),
    ]
